### ISSUE TITLE
Could not find com.mapbox.base:common:0.5.0

### ISSUE THREAD

**Issue by eygraber** [mapbox/mapbox-maps-android#1286] opened 2022-04-18 20:39 UTC
All of my builds fail with the following error:

```
[2022-04-18T20:34:26.332Z] * What went wrong:
[2022-04-18T20:34:26.332Z] Could not determine the dependencies of task ':app:generateDevReleaseLintModel'.
[2022-04-18T20:34:26.332Z] > Could not resolve all task dependencies for configuration ':app:devReleaseRuntimeClasspath'.
[2022-04-18T20:34:26.332Z]    > Could not find com.mapbox.base:common:0.5.0.
[2022-04-18T20:34:26.332Z]      Required by:
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.maps:base:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.extension:maps-style:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-logo:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-compass:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-gestures:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-attribution:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-locationcomponent:10.4.2
[2022-04-18T20:34:26.332Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-scalebar:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-overlay:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-annotation:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.extension:maps-localization:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-lifecycle:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-viewport:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.module:maps-telemetry:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.common:okhttp:21.2.1 > com.mapbox.common:common:21.2.1
[2022-04-18T20:34:26.333Z]    > Could not find com.mapbox.base:annotations:0.5.0.
[2022-04-18T20:34:26.333Z]      Required by:
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-attribution:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.plugin:maps-annotation:10.4.2
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.common:okhttp:21.2.1 > com.mapbox.common:common:21.2.1
[2022-04-18T20:34:26.333Z]    > Could not find com.mapbox.common:logger:0.5.0.
[2022-04-18T20:34:26.333Z]      Required by:
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.common:okhttp:21.2.1 > com.mapbox.common:common:21.2.1
[2022-04-18T20:34:26.333Z]    > Could not find com.mapbox.common:loader:0.5.0.
[2022-04-18T20:34:26.333Z]      Required by:
[2022-04-18T20:34:26.333Z]          project :app > project :features:map > com.mapbox.maps:android:10.4.2 > com.mapbox.common:okhttp:21.2.1 > com.mapbox.common:common:21.2.1
```

**Comment by mattijsf** [comment] 2022-04-19 08:34
Probably a duplicate of https://github.com/mapbox/mapbox-maps-android/issues/1285

**Comment by ank27** [comment] 2022-04-19 10:31
@eygraber Thank you for the issue. We are currently looking into it and will update as soon as it's fixed.

**Closed** 2022-04-19 13:37 UTC
Labels: bug :beetle:
