### ISSUE TITLE
The direction of user location marker is activated randomly

### ISSUE THREAD

**Issue by aDamian88** [mapbox/mapbox-maps-android#2166] opened 2023-09-06 12:06 UTC
## Environment

- Android OS version: 30 - 31
- Devices affected: Galaxy Nexus, Pixel 6 Pro
- Maps SDK Version: 10.0

## Observed behavior and steps to reproduce

The heading direction on the user location marker is activated randomly, even when the device is stationary or not rotated.

Interestingly, on the iOS MapBox implementation, we don't encounter these issues. It's possible that this behavior is influenced by the sensitivity of the GPS sensor.

https://github.com/mapbox/mapbox-maps-android/assets/25756325/817e03b9-f679-436a-b1b1-0331816f0871

## Expected behavior

The heading direction should be more stable.

**Comment by kiryldz** [comment] 2024-11-01 19:04
Duplicate of https://github.com/mapbox/mapbox-maps-android/issues/1391, closing.

**Closed by kiryldz** 2024-11-01 19:04 UTC
Labels: bug :beetle:
