### ISSUE TITLE
LocationPuck not showing

### ISSUE THREAD

**Issue by badoualy** [mapbox/mapbox-maps-android#1048] opened 2022-01-12 23:41 UTC
## Environment

- Android OS version: API 30 (v11)
- Devices affected:
- Maps SDK Version: 10.2.0

## Observed behavior and steps to reproduce

I'm using the SDK in Compose inside an `AndroidView`, and the LocatoinPuck is not showing most of the time (90%)
(see code below)

Note: the pulsing effect is showing properly

## Expected behavior

LocationPuck should always be visible

## Notes / preliminary analysis

Honnestly not sure what's happening, I tried checking the threading.
I tried waiting for the style to be loaded, same thing.

## Additional links and references

```kotlin
AndroidView(
    factory = { 
        MapView(it).apply {
            location.updateSettings {
                enabled = true
                locationPuck = buildLocationPuck()
                pulsingEnabled = true
            }
        
            getMapboxMap().setCamera(
                CameraOptions.Builder()
                    .center(Point.fromLngLat(7.902085, 49.028343))
                    .zoom(8.0)
                    .build()
            )
        }
    },
    modifier = Modifier.fillMaxSize()
)

fun MapView.buildLocationPuck(): LocationPuck2D {
    return LocationPuck2D(
        bearingImage = AppCompatResources.getDrawable(context, R.drawable.ic_location_puck),
        topImage = AppCompatResources.getDrawable(context, R.drawable.ic_location_puck),
        scaleExpression = literal(3.0).toJson()
    )
}
```

**Comment by Chaoba** [comment] 2022-01-12 23:57
@badoualy Are you able to receive the GPS signal? Try to go outside or close to the window.

**Comment by badoualy** [comment] 2022-01-13 00:46
@Chaoba Yes, the pulse animation is present, the GPS coordinates are received correctly, the onIndicatorLocationChangedListener is also called

**Comment by ZiZasaurus** [comment] 2022-01-21 15:49
@badoualy can you let us know if this behavior also happens on physical devices?

**Comment by yunikkk** [comment] 2022-02-01 17:11
The root cause of the issue is similar to #321. Fix is in progress, should be available in the next release.

**Closed** 2022-02-24 17:34 UTC
Labels: bug :beetle:
