### ISSUE TITLE
Unable to disable pinch rotation

### ISSUE THREAD

**Issue by christiankm** [mapbox/mapbox-maps-android#1784] opened 2022-10-31 23:02 UTC
## Environment

I’m on a Google Pixel 6, Android V 13
Maps SDK Version: 10.5.0

## Observed behaviour and steps to reproduce

I am unable to disable pinch rotation, and I have tried a couple of ways to do that

mapView.gestures.rotateEnabled = false

I also tried disabling the compass but that didn't seem to help

mapView.compass.enabled = false

## Expected behaviour

mapView.gestures.rotateEnabled = false should disable pinch rotation

## Notes / preliminary analysis

I am not sure if there is anything else I need to do, I couldn't find anything in the documentation

Reopened from #1551

**Comment by christiankm** [comment] 2022-10-31 23:07
https://user-images.githubusercontent.com/3626094/199126344-63363e87-9fac-4161-8033-38168b62cbed.mp4

**Comment by ZiZasaurus** [comment] 2022-11-01 13:04
@christiankm thank you for reaching out. Are you able to reproduce this behavior on v10.9, the latest version of our SDK?

**Comment by christiankm** [comment] 2022-11-02 00:45
@ZiZasaurus No problem. No, I don't believe we've tried later version of the SDK yet. We'll make sure to do that and get back to you.
If you could try on your end as well and confirm if you are able to reproduce, that would be great.

**Comment by ZiZasaurus** [comment] 2022-11-02 12:37
@christiankm, thank you for following up. I am unable to reproduce this behavior on our most recent version.

**Comment by ZiZasaurus** [comment] 2022-11-19 14:01
Closing this ticket but please feel free to reopen if the issue reoccurs.

**Closed by ZiZasaurus** 2022-11-19 14:01 UTC
Labels: bug :beetle:
