### ISSUE TITLE
Allow to turn off CameraAnimationPlugin logs

### ISSUE THREAD

**Issue by yuryybk** [mapbox/mapbox-maps-android#243] opened 2021-04-08 18:34 UTC
## New Feature
Allow to turn off CameraAnimationPlugin logs on the app side

## Why
CameraAnimationPlugin logs are too frequent and prevent analysis in some cases

**Comment by tobrun** [comment] 2021-05-24 14:52
Duplicate of internal ticket

**Comment by kiryldz** [comment] 2021-07-02 15:30
As additional request some frequent log messages will be downgraded to `verbose` instead of `info`

**Closed** 2021-07-05 10:56 UTC
Labels: feature :green_apple:
