### ISSUE TITLE
Untraceable crash in Projection.unproject

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#1277] opened 2022-04-13 10:33 UTC
## Environment

- Android OS version: Any
- Devices affected: Any
- Maps SDK Version: 10.x

## Observed behavior and steps to reproduce

I am seeing quite some users experiencing the following crash
```
Fatal Exception: java.lang.Error: latitude must not be NaN
       at com.mapbox.maps.Projection.unproject(Projection.java)
       at com.mapbox.maps.MapboxMap.unproject(MapboxMap.kt:773)
       at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory.getFlyTo$lambda-9(CameraAnimatorsFactory.kt:367)
       at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory.$r8$lambda$i0eVRz5Pdg1wufkPMzLCax34Kqw(CameraAnimatorsFactory.kt)
       at com.mapbox.maps.plugin.animation.CameraAnimatorsFactory$$InternalSyntheticLambda$0$9985f632ee5faaf5afb7ec31443bdd92f0c72cacbe52ded66cc57daeeb8aa2e1$0.evaluate(CameraAnimatorsFactory.java:42)
       at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
       at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1561)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1357)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1489)
       at android.animation.ValueAnimator.pulseAnimationFrame(ValueAnimator.java:1508)
       at android.animation.AnimatorSet.pulseFrame(AnimatorSet.java:1170)
       at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1150)
       at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1053)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1350)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
       at android.view.Choreographer.doFrame(Choreographer.java:1040)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:245)
       at android.app.ActivityThread.main(ActivityThread.java:8024)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

## Expected behavior

The app does not crash. 

## Notes / preliminary analysis

Due to the stacktrace it is impossible for me to determine the source of this issue. I am also unable to reproduce it. 
In order to try to solve this crash on my end I have sanity checks in place on all entry points to the mapbox animations framework that make sure that coordinates are within possible lat/lng bounds. Those do not have any effect.

**Comment by kiryldz** [comment] 2022-04-13 10:36
Closing as duplicate of https://github.com/mapbox/mapbox-maps-android/issues/1143, will be fixed in upcoming release.

**Closed by kiryldz** 2022-04-13 10:36 UTC
Labels: bug :beetle:
