### ISSUE TITLE
Android Auto map getting pixelated 

### ISSUE THREAD

**Issue by kapoorshivam** [mapbox/mapbox-maps-android#2241] opened 2023-12-19 10:02 UTC
## Environment

- Android OS version: 14
- Devices affected: SM-S908B, SM-S901B
- Maps SDK Version: 10.12.0

## Observed behavior and steps to reproduce

On some Samsung devices(Galaxy S22) with Android 14 map is getting pixelated on Android Auto, but Actions icons are properly visible. So, looks like the issue is only with displaying maps. 

Fews Images + Video for reference
![20231218_165937](https://github.com/mapbox/mapbox-maps-android/assets/16036532/57da7a22-441b-44e8-b91e-cc65f4733b76)
![20231218_170044](https://github.com/mapbox/mapbox-maps-android/assets/16036532/66ccd584-4395-4e00-91a9-a339a5ba7374)

https://drive.google.com/file/d/1WXjH-72hQvA3p8YVWAvX2tn7H3OuqnXw/view?usp=sharing
https://drive.google.com/file/d/1R82UKnjnLW4JPLdd1ML6-ZqJ-MlY7LwK/view?usp=sharing

Other Observations:-
It was working fine on Android 13 but when user updated to Android 14 it started breaking. 
Other devices might be facing similar issue but haven't received any  reported issue for them

**Comment by kiryldz** [comment] 2023-12-19 10:52
@kapoorshivam there might be different reasons for that however we did fix some issues related to that kind of rendering in https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.16.3. Can you give a try and see if this fixes the issue?

**Comment by kapoorshivam** [comment] 2023-12-19 11:50
@kiryldz Hi, thanks will try using latest version

**Comment by baleboy** [comment] 2023-12-21 06:02
Hi @kapoorshivam , did patch 10.16.3 fix the issue for you?

**Comment by kapoorshivam** [comment] 2023-12-22 09:23
Hi @baleboy build with patch 10.16.3 is shared with the user, waiting for the feedback. Will update the ticket

**Comment by kapoorshivam** [comment] 2023-12-26 09:33
Hi @baleboy with patch 10.16.3  user is not facing any issue, so closing this ticket
Thanks for the help

**Comment by kapoorshivam** [comment] 2024-01-15 13:18
After updating to `10.16.4 ` one of the user is getting this issue.

<img width="495" alt="widget" src="https://github.com/mapbox/mapbox-maps-android/assets/16036532/e1aa2e24-07e0-4463-a15f-eae9cc744326">

Map is properly visible but widgets background is pixelated now

**Comment by kiryldz** [comment] 2024-01-15 15:18
@kapoorshivam do you happen to know what device model is that? also does this happen all the time or occasionally?

**Comment by kapoorshivam** [comment] 2024-01-16 09:31
@kiryldz Device is Pixel 8, Android 14. yes this is happening all the time

**Comment by kapoorshivam** [comment] 2024-01-24 13:20
@kiryldz any updates on this ?

**Comment by kiryldz** [comment] 2024-01-26 15:02
@kapoorshivam no, we will for sure let you know when there will be updates.

**Comment by kapoorshivam** [comment] 2024-02-14 08:23
Hi @kiryldz, do we have any ETA for when this will be fixed? Many users have now started reporting this issue.

**Comment by kiryldz** [comment] 2024-02-14 09:13
@kapoorshivam we do not have the estimate right now. Can you perhaps share any new details what Android devices / Android versions are affected?

**Comment by kapoorshivam** [comment] 2024-02-15 11:01
Android 14
Samsung phones(Galaxy S22 Ultra, Galaxy S22) and some Devices Pixel 8

**Comment by kapoorshivam** [comment] 2024-02-19 10:46
@kiryldz As more user's have started reporting similar issue and all of them are on Android-14 and are using devices like Pixel 8, Pixel 8 Pro, Galaxy S22 Ultra, S22+, S22. 
I can see that a similar issue, #2251 , has been reported. so are there any other similar reported issues?
Just wanted to know how many users are facing this type of issue so that we can get an idea about the widespread nature of this problem.

**Comment by kapoorshivam** [comment] 2024-03-01 08:04
Hi @kiryldz, any update on this?  Reports of this issue are increasing day by day

**Comment by kiryldz** [comment] 2024-03-01 08:12
@kapoorshivam we are looking into it. It seems that root cause is found however there are no clear estimates when this will be fixed. If there will be some more concrete details about timeline - I'll share them here.

**Comment by kiryldz** [comment] 2024-03-06 11:56
@kapoorshivam can you please try `10.16.6-SNAPSHOT.0306T1139Z.764ecaa` snapshot built on top of v10.16.6 (please [add](https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#use-snapshot-releases-in-your-app) a snapshot mirror to resolve it)? If I get it right you can reproduce the issue locally so you could easily verify it. Also - if it works for you locally and you don't mind using snapshot in production - can you share that fix with users to gather feedback? We don't have any plans to release v10.16.7 in the nearest future.

**Comment by kiryldz** [comment] 2024-03-18 14:21
@kapoorshivam any feedback so far?

**Comment by kiryldz** [comment] 2024-04-10 12:43
Fixed in https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.17.0

**Closed by kiryldz** 2024-04-10 12:43 UTC
Labels: bug :beetle:

**Comment by AkshatDubey10** [comment] 2024-10-29 13:01
hey @kiryldz user are facing the same pixelated map issue again. I have attached the photos for reference
Mapbox version - 10.18.2


![image-min](https://github.com/user-attachments/assets/a89b8170-b17f-4014-8761-294b916eb752)
<img width="676" alt="image" src="https://github.com/user-attachments/assets/863af343-4eaf-441b-a189-47d39ba0a270">
<img width="676" alt="image" src="https://github.com/user-attachments/assets/44ff24ef-697b-4925-b129-8207832c062a">
