### ISSUE TITLE
View Annotations not visible

### ISSUE THREAD

**Issue by VincentJoshuaET** [mapbox/mapbox-maps-android#870] opened 2021-11-19 00:41 UTC
## Environment

- Android OS version: 12
- Devices affected: Samsung Galaxy S20+
- Maps SDK Version: 10.2.0-beta.1

## Observed behavior and steps to reproduce

I just used this basic code. 

```
                            features.forEach { feature ->
                                val title = feature.getStringProperty("title")
                                val subtitle = feature.getStringProperty("subtitle")
                                val view = binding.mapView.viewAnnotationManager.addViewAnnotation(
                                    R.layout.layout_bubble,
                                    viewAnnotationOptions {
                                        geometry(feature.geometry()!!)
                                        associatedFeatureId(feature.id()!!)
                                        allowOverlap(true)
                                    }
                                )
                                LayoutBubbleBinding.bind(view).apply {
                                    textViewTitle.text = title
                                    textViewSubtitle.text = subtitle
                                    textViewSubtitle.isVisible = subtitle != null
                                }
                            }
```

## Expected behavior

No annotation shows up. I can confirm that the list of features is not empty, and that the id and geometry are not null.

## Notes / preliminary analysis

I tried also using the asynclayoutinflater, or manually inflating the view, but no help. I tried setting the `attachToRoot` boolean to true when inflating the view, it shows up but the annotation is stuck on the upper left corner. I tried setting the view annotation option visible value to true, and not setting it (null) but it does not help.

I can also verify that the Layout resource specifies that the view is visible.

**Comment by kiryldz** [comment] 2021-11-19 07:12
@VincentJoshuaET thanks for early 👀 on this functionality!

Based on code provided I can only suppose that `featureId` simply does not exist on map. Try removing `associatedFeatureId(feature.id()!!)` and see if views will appear. Please keep in mind that `associatedFeatureId` only controls view annotation visibility based on feature visibility but does not control actual positioning in the viewport, positioning should be adjusted using `anchor` + `offsetX`, `offsetY` if needed.

Please check out our [example](https://github.com/mapbox/mapbox-maps-android/blob/main/app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt) to see how to make it all work properly.

Let me know if it will help and re-open issue if needed.

**Comment by VincentJoshuaET** [comment] 2021-11-19 07:13
Yes. I tried removing feature.id() but the annotation still doesn't show up.

**Comment by VincentJoshuaET** [comment] 2021-11-19 07:20
Also, if the feature does not exist, It should cause a null pointer exception, right?

**Comment by kiryldz** [comment] 2021-11-19 07:34
> Yes. I tried removing feature.id() but the annotation still doesn't show up.

Re-opening then. Please take a look at the example I've provided you in https://github.com/mapbox/mapbox-maps-android/issues/870#issuecomment-973810908. I can not see any reasons why your view is not showing up, unless you did specify it as `View.GONE` or `View.INVISIBLE` in xml layout file.



> Also, if the feature does not exist, It should cause a null pointer exception, right? There is no log reported at all that indicates what is wrong.
> 
> I tried using it with AsyncLayoutInflater and have received the callback being invoked, but the view is not visible.

I'll create a follow-up task for that, indeed exception should be thrown, thanks for flagging. I verified locally that if non-existent `featureId` is used - no view annotation will be shown.

**Comment by kiryldz** [comment] 2021-11-19 07:49
@VincentJoshuaET I've tried it locally and indeed you're right - if setting no `associatedFeatureId` at all - no view annotation is shown 😞 We will try to fix it ASAP but as for now you could workaround by actually providing correct `featureId`s - then it will work fine.

**Comment by VincentJoshuaET** [comment] 2021-11-19 07:53
I am not sure why this is not showing up:

```
                            val features = mapboxMap.queryRenderedFeatures(
                                box,
                                "red-point-iot-graphics-layer"
                            )

                            Timber.tag("MapFragment").d("Query rendered features:")
                            features.forEach { feature ->
                                Timber.tag("MapFragment").d("Feature with ID - %s and Geometry - %s", feature.id(), feature.geometry())
                                val title = feature.getStringProperty("title")
                                val subtitle = feature.getStringProperty("subtitle")
                                val view = binding.mapView.viewAnnotationManager.addViewAnnotation(
                                    R.layout.layout_bubble,
                                    viewAnnotationOptions {
                                        geometry(feature.geometry()!!)
                                        associatedFeatureId(feature.id()!!)
                                        allowOverlap(true)
                                    }
                                )
                                with(LayoutBubbleBinding.bind(view)) {
                                    textViewTitle.text = title
                                    textViewSubtitle.text = subtitle
                                    textViewSubtitle.isVisible = subtitle != null
                                }
                            }
```

Note: I made a suspending extension function for queryRenderedFeatures.

Log:
```
D/MapboxUtil: Querying Mapbox rendered Features with ids red-point-iot-graphics-layer, inside box [min: [x: 612.8027343744759, y: 750.8203125028824], max: [x: 642.8027343744759, y: 780.8203125028824]], and filter null
D/InputTransport: Input channel destroyed: 'ClientS', fd=199
D/InputTransport: Input channel destroyed: 'ClientS', fd=209
D/MapboxUtil: Rendered features: Feature{type=Feature, bbox=null, id=00010000-00000000-03591800-83307535, geometry=Point{type=Point, bbox=null, coordinates=[69.59630727767944, 41.49882285113725]}, properties={REDACTED}}
D/MapFragment: Query rendered features:
D/MapFragment: Feature with ID - 00010000-00000000-03591800-83307535 and Geometry - Point{type=Point, bbox=null, coordinates=[69.59630727767944, 41.49882285113725]}
```

**Comment by VincentJoshuaET** [comment] 2021-11-19 08:04
I tried inflating the view manually and attaching to root, like this:

```
                            val features = mapboxMap.queryRenderedFeatures(
                                box,
                                "red-point-iot-graphics-layer"
                            )

                            Timber.tag("MapFragment").d("Query rendered features:")
                            features.forEach { feature ->
                                Timber.tag("MapFragment").d("Feature with ID - %s and Geometry - %s", feature.id(), feature.geometry())
                                val title = feature.getStringProperty("title")
                                val subtitle = feature.getStringProperty("subtitle")
                                val bubble = LayoutBubbleBinding.inflate(layoutInflater, binding.mapView, true).apply {
                                    textViewTitle.text = title
                                    textViewSubtitle.text = subtitle
                                    textViewSubtitle.isVisible = subtitle != null
                                }
                                binding.mapView.viewAnnotationManager.addViewAnnotation(
                                    bubble.root,
                                    viewAnnotationOptions {
                                        geometry(feature.geometry()!!)
                                        associatedFeatureId(feature.id()!!)
                                        allowOverlap(true)
                                    }
                                )
                            }
```

And this happens:
![Screenshot_20211119-160334_GeoViewer Mobile Debug](https://user-images.githubusercontent.com/19756326/142587216-4671fbf6-63c2-4fc0-b30b-3e7e043f9688.png)

Setting attachToRoot to false will make it not show up like before.

**Comment by kiryldz** [comment] 2021-11-19 09:36
@VincentJoshuaET I've taken a deeper look and there should be no issue if adding view annotation to the point even if no `associatedFeatureId` is specified as I wrote in https://github.com/mapbox/mapbox-maps-android/issues/870#issuecomment-973837771. 

Can it be somehow connected with view bindings you are using? Can you try following code:
```
features.forEach { feature ->
    val title = feature.getStringProperty("title")
    val subtitle = feature.getStringProperty("subtitle")
    val view = binding.mapView.viewAnnotationManager.addViewAnnotation(
        R.layout.layout_bubble,
        viewAnnotationOptions {
            geometry(feature.geometry()!!)
            associatedFeatureId(feature.id()!!)
            allowOverlap(true)
        }
    )
    view.apply {
        findViewById<TextView>(R.id.textViewTitle).text = title
        findViewById<TextView>(R.id.textViewSubtitle).text = subtitle
        findViewById<TextView>(R.id.textViewSubtitle).isVisible = subtitle != null
    }
}
```
and make sure that `layout_bubble` is visible.
Also would be nice if you could prepare share some actual small project of yours where adding view annotation does not work, I'll be happy to have a look.

**Comment by kiryldz** [comment] 2021-11-19 10:20
@VincentJoshuaET I've prepared basic example very similar to your setup, PTAL at https://github.com/mapbox/mapbox-maps-android/pull/873.
During development one thought came to my mind, could you please check that your `layout_bubble.xml` _does not_ use `WRAP_CONTENT` dimensions for width and height? Only fixed dimensions are supported for now.

**Comment by VincentJoshuaET** [comment] 2021-11-19 10:23
Unfortunately, my layout does use WRAP_CONTENT. Any suggestions for a workaround? I have two textviews that can have differing lengths depending on the feature. Thank you.

**Comment by VincentJoshuaET** [comment] 2021-11-19 10:24
Ill try to use fixed dimensions with autosizing textviews. Ill update you next week as it's already Friday night for me

**Comment by kiryldz** [comment] 2021-11-19 10:41
tracking with https://github.com/mapbox/mapbox-maps-android/issues/874

**Comment by kiryldz** [comment] 2021-11-19 10:41
@VincentJoshuaET closing this one as it should be root cause in your case, please re-open if needed.

**Closed by kiryldz** 2021-11-19 10:41 UTC
Labels: bug :beetle:

**Comment by VincentJoshuaET** [comment] 2021-11-21 23:27
> @VincentJoshuaET I've prepared basic example very similar to your setup, PTAL at #873. During development one thought came to my mind, could you please check that your `layout_bubble.xml` _does not_ use `WRAP_CONTENT` dimensions for width and height? Only fixed dimensions are supported for now.

Will wrap_content dimensions be supported in the future?

**Comment by VincentJoshuaET** [comment] 2021-11-25 06:33
I tried to set my root layout dimensions as fixed, but the views inside still set as WRAP_CONTENT. Will this not work still?

**Comment by OliverCulleyDeLange** [comment] 2023-06-20 14:37
For anyone else stumbling accross this issue with a similar issue while trying to use mapbox with compose - a [workaround](https://github.com/mapbox/mapbox-maps-android/commit/b513f0aaaea5c3c410b45486766f4fb75e4426cd) i'm using is to manually measure the view before adding it to the map.
It looks like the [global layout listener](https://github.com/mapbox/mapbox-maps-android/blob/49397adcd04443fcbd403b8763b56952ce362fbb/sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt#L427) mapbox are using to handle wrap_content sized views isn't being called when wrapped in a compose `AndroidView`. 

```kotlin
        val view = LayoutInflater.from(context).inflate(R.layout.item_callout_view, mapView, false)
        view.measure(
          MeasureSpec.makeMeasureSpec(mapView.width,MeasureSpec.AT_MOST),
          MeasureSpec.makeMeasureSpec(mapView.height,MeasureSpec.AT_MOST)
        )
        view.updateLayoutParams {
         this.height =  view.measuredHeight
          this.width = view.measuredWidth
        }
        viewManager.addViewAnnotation(
          view,
          viewAnnotationOptions {
            geometry(point)
            anchor(ViewAnnotationAnchor.BOTTOM)
            allowOverlap(false)
          },
        )

```
