### ISSUE TITLE
Unsafe park crash/anr

### ISSUE THREAD

**Issue by kruid9403** [mapbox/mapbox-maps-android#1998] opened 2023-02-08 15:47 UTC
## Environment

Android 13 primarily 1 instance on Android 12
Observed mostly on Galaxy and Pixel devices

The project uses Jetpack Compose

I have tried

    implementation 'com.mapbox.plugin:maps-logo:10.10.0'
    implementation 'com.mapbox.maps:android:10.10.0'
and 10.8.0

with the same result.

## Observed behavior and steps to reproduce

I am receiving crash reports from Firebase Crashlytics on various devices.

I am unable to reproduce the crash on my devices but get the following crash report:

main (waiting):tid=1 systid=8783 
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at com.mapbox.maps.renderer.MapboxRenderThread.onSurfaceCreated(MapboxRenderThread.kt:470)
       at com.mapbox.maps.renderer.MapboxSurfaceRenderer.surfaceChanged(MapboxSurfaceRenderer.kt:34)
       at com.mapbox.maps.renderer.MapboxSurfaceHolderRenderer.surfaceChanged(MapboxSurfaceHolderRenderer.kt:16)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1154)
       at android.view.SurfaceView.lambda$new$0$android-view-SurfaceView(SurfaceView.java:200)
       at android.view.SurfaceView$$ExternalSyntheticLambda5.onPreDraw(SurfaceView.java:2)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1121)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4317)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2991)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10665)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

I wish I had more information for you but this is all I have. It is not a consistent issue small number of users.

**Comment by kiryldz** [comment] 2023-02-21 10:47
@kruid9403 thanks for flagging! is there any chance you also have the logs (and not just the exception) before ANR happens?

**Comment by kruid9403** [comment] 2023-02-21 11:39
I have 98 threads that are associated with the crash report. I do not have any logs beyond that.

**Comment by kruid9403** [comment] 2023-02-21 17:07
@kiryldz We did finally get a reproductions. What level of logging do you want?

**Comment by kiryldz** [comment] 2023-02-21 18:38
All the device logs let's say 10 seconds before ANR occurs.
Also - do I read it correctly that you could reproduce it? If yes, steps to reproduce will be much appreciated

**Comment by kruid9403** [comment] 2023-02-22 15:14
@kiryldz We may have found a work around. We moved some things around and changed the order of operations and the error seems to have gone away in the dev environment at least. I will open another ticket if it persists in prod.

**Comment by kruid9403** [comment] 2023-03-27 14:17
Just a follow up:

I have been able to drastically reduce but not eliminate this issue in production. The app has a somewhat heavy map with several hundred view annotations that frequently get updated for size and colors. In addition there are several other things going on while this is happening.

I did some work to reduce the overall weight of this screen such as moving the location permission check and a couple overlays from this screen to their own composables. It is possible that the phone is throwing this error when the real issue is a lack of resources to complete the functions in progress.

**Comment by Waboodoo** [comment] 2023-03-31 10:18
Similar for us. In our latest release, the number of ANR in production has gone down by a lot (still happening occasionally). The main change was that we reduced the number of map features from 500 to about 100. We also moved some other workload onto dedicated worker pools, so overall the ANRs might really be a symptom of resource constraints.

**Comment by kiryldz** [comment] 2023-04-14 12:05
Thanks for the comments. From what I see no action could be done from Mapbox end so closing this one. If any particular details will pop up, feel free to re-open or open the new issue with detailed description.

**Closed by kiryldz** 2023-04-14 12:05 UTC
Labels: bug :beetle:

**Comment by kiryldz** [comment] 2023-04-25 10:22
@kruid9403 @Waboodoo informing that I did actually find the root cause leading to that ANR and this will be fixed in `v10.13.0` upcoming next week. There were indeed rare situations when Android was marking current `Surface` used for drawing as invalid and sending the new valid one (most likely happening when bringing app to front from background) - and if getting unlucky with race conditions - that could have caused the ANR you reported in our renderer.

**Comment by Waboodoo** [comment] 2023-04-25 15:09
Cool, glad to hear, thanks. I'll give it a try once it's out 👍🏻

**Comment by kruid9403** [comment] 2023-04-25 15:22
Excellent, thanks.

**Comment by Amritpal33** [comment] 2023-08-25 06:18
Hi @kiryldz, Although un-related to Mapbox, we are also facing similar anr in our project. Can you pls share some insights on how have you solved this ? Are there any checks that we need to keep in-place once the app comes to foreground ?

Appreciate if you can help. Thanks.
