### ISSUE TITLE
FillExtrusionLayer is inside out

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-maps-android#142] opened 2021-03-02 18:56 UTC
## Environment

- Maps SDK Version: 10.0.0-beta.13

## Observed behavior and steps to reproduce

| style.addLayerAbove(layer, "building-outline") | style.addLayer(layer) |
| -- | -- |
| <img width="353" alt="Screen Shot 2021-03-02 at 10 47 55 AM" src="https://user-images.githubusercontent.com/3021882/109699086-fa2a4980-7b44-11eb-9c02-90b28154fc71.png"> | <img width="353" alt="Screen Shot 2021-03-02 at 8 45 09 AM" src="https://user-images.githubusercontent.com/3021882/109682799-9a777280-7b33-11eb-8d9b-23a583091bf3.png"> |

## Expected behavior

It may be my own confusion, but why does the layer you render relative to another layer affect the shape? I would expect the layer to only be a "draw order".

Here's the draft where I'm reproducing https://github.com/mapbox/mapbox-navigation-android/pull/4078

**Comment by kmadsen** [comment] 2021-03-02 19:51
Possibly related issue, but I'm not sure how to make the building alpha work. The building on the right should have some transparency

``` kotlin
val layer = FillExtrusionLayer(layerId, sourceId)
    .fillExtrusionColor(Color.argb(0xB2, 0xD6, 0x02, 0xEE)) 
```

**Comment by kmadsen** [comment] 2021-05-12 22:13
> is this still an issue in more recent releases?

@knov I just reproduced on `10.0.0-beta.19`, so it is still happening.

I also want to note that, it is not blocking progress. Shipped building highlights without specifying the layer position.

**Comment by Chaoba** [comment] 2021-06-25 08:18
@kmadsen The root cause for this should be that your layer is covered by "building" layer, so if you add your layer above "building" layer, this should be fixed.
Can you try it on your side?

**Comment by tobrun** [comment] 2021-06-30 12:55
Works as designed. Closing

**Closed by tobrun** 2021-06-30 12:55 UTC
Labels: bug :beetle:, p2
