### ISSUE TITLE
Types of certain fields of the properties of a feature are not kept

### ISSUE THREAD

**Issue by belgianwaves** [mapbox/mapbox-maps-android#2197] opened 2023-10-19 09:32 UTC
## Environment

- Android OS version: all versions
- Devices affected: all devices
- Maps SDK Version: since 10.11.x

## Observed behaviour and steps to reproduce

When i create a layer through a feature (fetched from server as json) certain fields of the properties of the feature are of type int. When i later click on that layer to query the feature those fields of the properties of type int have changed to doubles (for example "1" has changed to "1.0"). 

## Expected behaviour

Offering features and later querying those feature should keep the type of the fields of the properties of a feature

## Notes / preliminary analysis

Bug seems to be present starting from version 10.11.x, older versions don't have this behaviour,
making us stuck on version 10.10.2

**Comment by kiryldz** [comment] 2024-11-01 19:06
If this is still an issue with latest release - please provide the reproducible example, this will help us to fix this faster if the issue is on our side. Closing for now, please re-open if needed.

**Closed by kiryldz** 2024-11-01 19:06 UTC
Labels: bug :beetle:
