### ISSUE TITLE
Memory Leak in ViewAnnotationManager

### ISSUE THREAD

**Issue by florianPOLARSTEPS** [mapbox/mapbox-maps-android#1535] opened 2022-07-25 16:05 UTC
## Environment

- Android OS version: Any
- Devices affected: Irrelevant
- Maps SDK Version: 10.7.0-rc1 (but probably 10.6.x as well)

## Observed behavior and steps to reproduce

There seems to be another memory leak related to the new ViewAnnotationManager. 
This happens when a Fragment (holding a MapView) is added and removed a couple of times. Please refer to the sample project provided to reproduce the issue.

It's quite a big problem for us since we are using maps in quite a lot of different fragments and users navigate out and in of those a lot. 

```
┬───
│ GC Root: Global variable in native code
│
├─ com.mapbox.maps.ViewAnnotationManagerImpl instance
│    Leaking: UNKNOWN
│    Retaining 19.4 kB in 635 objects
│    ↓ ViewAnnotationManagerImpl.mapView
│                                ~~~~~~~
╰→ com.mapbox.maps.MapView instance
​     Leaking: YES (ObjectWatcher was watching this because com.example.mapboxleak.LeakMapFragment received
​     Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks))
​     Retaining 5.2 kB in 147 objects
​     key = b1850cd2-26cc-418b-ba94-8356fa1733db
​     watchDurationMillis = 7725
​     retainedDurationMillis = 2723
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of com.example.mapboxleak.MapboxLeakActivity with mDestroyed = false

METADATA

Build.VERSION.SDK_INT: 31
Build.MANUFACTURER: Google
LeakCanary version: 2.9.1
App process name: com.example.mapboxleak
Class count: 23105
Instance count: 192434
Primitive array count: 131825
Object array count: 27579
Thread count: 44
Heap total bytes: 24807728
Bitmap count: 5
Bitmap total bytes: 244563
Large bitmap count: 0
Large bitmap total bytes: 0
Db 1: open /data/user/0/com.example.mapboxleak/no_backup/androidx.work.workdb
Stats: LruCache[maxSize=3000,hits=106901,misses=187696,hitRate=36%]
RandomAccess[bytes=9235953,reads=187696,travel=55342807221,range=30180111,size=37323298]
Analysis duration: 4140 ms
```

## Expected behavior

No memory leak

## Notes / preliminary analysis

The root of this Memory leak seems to be in Native code

## Additional links and references

Sample project demonstrating the issue (reused from the last memory leak I found in that component)
https://github.com/florianPOLARSTEPS/MapboxAnnotationLeak

**Comment by ZiZasaurus** [comment] 2022-07-26 23:09
@florianPOLARSTEPS thank you for reporting. The team is looking into what could be causing this behavior.

**Comment by kiryldz** [comment] 2022-07-29 13:26
@florianPOLARSTEPS I did identify the root cause and fixed that in core. Fix should be there in v10.8.0-beta.1.

**Comment by carlosvaccari** [comment] 2022-08-10 14:25
@kiryldz What is the expectation for v10.8.0-beta.1 to be release? Tks!

**Comment by kiryldz** [comment] 2022-08-10 14:29
@carlosvaccari it should be out this week.

**Comment by kiryldz** [comment] 2022-08-12 13:14
https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.8.0-beta.1 is out, should be fixed. If issue persists, please feel free to re-open.

**Closed by kiryldz** 2022-08-12 13:14 UTC
Labels: bug :beetle:

**Comment by florianPOLARSTEPS** [comment] 2022-08-13 04:34
@kiryldz thanks. I'm currently out of office. Will double-check once back.

**Comment by florianPOLARSTEPS** [comment] 2022-09-02 07:57
@kiryldz I can confirm it's working starting `10.8.x`. 👍
