### ISSUE TITLE
Can't get user location on Android 10

### ISSUE THREAD

**Issue by huahua8893** [mapbox/mapbox-maps-android#1821] opened 2022-11-08 18:41 UTC
I'm run the official demo "mapbox-maps-android" on device Android 12, and it's work correctly like this:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/10332761/200648330-ed8935cf-963d-47a1-8d77-1a3bd4ed8567.png">

But when I run the same demo on another device Android 10, it's can't get user location. Like this:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/10332761/200648430-d26bd4f0-9cef-4b07-ba89-d238576abea4.png">

And others map library does work on the device Android 10, So the device is not the problem. Is there any suggestion on this? Thank you.

**Comment by Haoming-Wu92** [comment] 2022-11-09 19:13
using 10.9.0
It works fine on my 10, 11, 12 devices (not the demo, my personal project)
I'm also using the google service suggested by mapbox in the docs.

Kinda weird your status bar is not showing the GPS icon on the 10 device

I initialized with these settings (kotlin)
```
mapView.location.updateSettings {
            enabled = true
            pulsingEnabled = true
        }

mapView.location2.updateSettings2 {
    puckBearingSource = PuckBearingSource.HEADING
    puckBearingEnabled = true
}
```

**Comment by ZiZasaurus** [comment] 2022-11-17 00:12
@huahua8893 I am also unable to reproduce this behavior. Do you have another device on which you are able to test? Is location turned on on your device?

**Comment by ZiZasaurus** [comment] 2022-12-06 15:30
Closing this ticket, but please feel free to reopen with the requested information if you continue to experience issues.

**Closed by ZiZasaurus** 2022-12-06 15:30 UTC
Labels: bug :beetle:
