### ISSUE TITLE
Error 403 when performing gradle sync of android test app

### ISSUE THREAD

**Issue by albertocappellina** [mapbox/mapbox-maps-android#320] opened 2021-05-10 09:27 UTC
## Environment

- Android Studio 4.2

## Observed behavior and steps to reproduce

I've imported android test app (https://github.com/mapbox/mapbox-maps-android) and opened mapbox-maps-android-main/app in android studio.

Setted secret/public token as reported here (https://docs.mapbox.com/android/beta/maps/guides/install/). (i provided all permission to my token just to see if this could resolve issue)

when i sinch i receive this error 

 > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden

## Expected behavior

sych is completed with no error

## Additional links and references

here's part of the gradle i use

buildscript {
  repositories {
    google()
    jcenter()
    maven {
      url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
      credentials {
        username = "mapbox"
        password = "sk.eyJ1IjoiaW50ZXN5 ...TRUNKED.... NyaDFrIn0.yWnO-0B1ZV8C6ZoTbYx7Ww"
      }
      authentication {
        create<BasicAuthentication>("basic")
      }
    }
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }

....

Thanks in advance,
Alberto

**Comment by kiryldz** [comment] 2021-05-10 13:54
Hey @albertocappellina, could you please paste complete version of you `build.gradle` project level file?

**Comment by albertocappellina** [comment] 2021-05-10 15:07
adding `SDK_REGISTRY_TOKEN` to system env does not help.
if i remove `classpath(Plugins.mapboxSdkRegistry)` from buld.gradle i can proceed with compilation but later i have this new error: 

`A problem occurred evaluating script.
> Plugin with id 'com.mapbox.sdkRegistry' not found.`

fyi i'm trying to build your own (test) app, not an app i built.

Thanks

**Comment by JavierSantanaNYC** [comment] 2021-06-01 13:35
> Could you please add env variable `SDK_REGISTRY_TOKEN` with your token or add it to `gradle.properties` and try to sync again? Or alternatively remove `classpath(Plugins.mapboxSdkRegistry)` from your `build.gradle` project level file.

Removing the mapbox sdkregistry from the class path worked for us - only issue is that you have to remove references to the publish.gradle file since we cant get to the mapbox sdkregistry (403 - Forbidden whenever we try to connect)

**Comment by PaulC-ManyHats** [comment] 2021-06-14 21:37
I too am also hitting this same error when building your own "**app**" (using today's main branch). 

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Mapbox Maps Android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
     Required by:
         project :
      > Could not resolve com.mapbox.gradle.plugins:sdk-registry:0.4.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/sdk-registry/0.4.0/sdk-registry-0.4.0.pom'. Received status code 403 from server: Forbidden`

I don't quite know what JavieSantanaNYC did because there is no such file as "publish.gradle" for me.

I tried to remove classpath(Plugins.mapboxSdkRegistry) which took me down a rabbit hole of removing references but for me it came to a deadend.

Someone should try building the app from scratch if possible and make sure ALL steps are documented, it seems like something is missing here for us new users.

**Comment by kiryldz** [comment] 2021-06-15 15:27
@PaulC-ManyHats - this is an issue in our distribution system and it will be fixed ASAP.

As temporary workaround could you please try do the following if building code from source:

1.  Make sure again you provided correct token with correct permissions (instructions could be found [here](https://docs.mapbox.com/android/beta/maps/guides/install/)).
2. Go to https://github.com/mapbox/mapbox-maps-android/blob/33f4643e65db1a655b9908755b62b94e98e811e8/build.gradle.kts#L26
and comment this line out.
3. Go with global replace for the project (Shift + Cmd + R on Mac) and also comment out applying SDK Registry plugin for all module level `build.gradle.kts` files like this

![image](https://user-images.githubusercontent.com/15800566/122080743-312c1e80-ce07-11eb-85c2-08921a4aa926.png)
4. Press `Sync Project with Gradle files` button in Android Studio.

**Comment by PaulC-ManyHats** [comment] 2021-06-15 18:06
@kiryldz - Today this workaround worked!  Not sure if I had some other changes previously that were preventing me, but I did a full clean, and fetch/pull of "main" branch, applied your suggestions and the app is running for me.  Thanks!

**Comment by kiryldz** [comment] 2021-06-22 12:42
We've fixed the root cause, now it should work fine (I validated that with new fresh token).
If the issue will persist - feel free to reopen this issue.

**Closed by kiryldz** 2021-06-22 12:42 UTC
Labels: bug :beetle:

**Comment by tir38** [comment] 2022-06-09 03:18
Any chance this is happening again? I'm hitting the same issue:

1. clone repo
2. create a new secrete token w/ `DOWNLOADS:READ` scope
3. copy token into `build.gradle.kts`

```
  credentials {
        username = "mapbox"
        password = "sk......."
      }
```

```
> Could not resolve all files for configuration ':sdk-base:releaseCompileClasspath'.
   > Could not resolve com.mapbox.maps:android-core:10.6.0-rc.1.
     Required by:
         project :sdk-base
      > Could not resolve com.mapbox.maps:android-core:10.6.0-rc.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.6.0-rc.1/android-core-10.6.0-rc.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.6.0-rc.1/android-core-10.6.0-rc.1.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.common:common:22.0.0-rc.2.
     Required by:
         project :sdk-base
      > Could not resolve com.mapbox.common:common:22.0.0-rc.2.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/common/22.0.0-rc.2/common-22.0.0-rc.2.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/common/22.0.0-rc.2/common-22.0.0-rc.2.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.mapbox.base:common:0.8.0.
     Required by:
         project :sdk-base
      > Could not resolve com.mapbox.base:common:0.8.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/base/common/0.8.0/common-0.8.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/base/common/0.8.0/common-0.8.0.pom'. Received status code 403 from server: Forbidden
```

**Comment by yunikkk** [comment] 2022-06-09 12:57
@tir38 seem to be working fine for me, is the token copied correctly?

**Comment by tir38** [comment] 2022-07-22 16:14
Plz ignore my prev comment. I had the correct password for the `buildscript` block, but was using my public key for the `allprojects` block.
