### ISSUE TITLE
Can the map  set the star background？？？？

### ISSUE THREAD

**Issue by zhufeixiang** [mapbox/mapbox-maps-android#971] opened 2021-12-10 03:27 UTC
when the MapProjection is MapProjection.Globe, can the map  set the star background？？？

**Comment by ank27** [comment] 2021-12-10 08:30
Duplicate of https://github.com/mapbox/mapbox-maps-android/issues/921

**Comment by zhufeixiang** [comment] 2021-12-10 08:33
> Duplicate of #921

thank you very much!!

**Closed** 2021-12-10 09:15 UTC
