### ISSUE TITLE
GetStyle callback is never triggered for LocationComponentPlugin

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-maps-android#321] opened 2021-05-10 18:14 UTC
### Affected versions
- `v10.0.0-beta.18` ✅ 
- `v10.0.0-beta.19` ❌ 

### Confusion on API

A downstream application is using `LocationComponentPlugin`, which implements `LifecyclePlugin`. Is it the responsibility of the downstream app to call `onStart` and `onStop`? It seems like it should be the `MapController` since it has the `pluginRegistry`

Is this because the `LocationComponentPlugin` should be added to the `MapPluginRegistry`?

### More info
1. The new [StyleObserver clears the list before notifying downstream observers](https://github.com/mapbox/mapbox-maps-android/blame/main/sdk/src/main/java/com/mapbox/maps/StyleObserver.kt#L33)
2. This can happen from regular Fragment lifecycle events, such as `onStart`
3. This causes the `LocationComponentPlugin` to never load the style in `activateLocationComponent`

(the numbers are associated with code screenshots)

1. ![Screen Shot 2021-05-10 at 9 56 37 AM](https://user-images.githubusercontent.com/3021882/117696319-04d11280-b176-11eb-89dc-e5829caaf2bf.png)

2. ![Screen Shot 2021-05-10 at 10 00 41 AM](https://user-images.githubusercontent.com/3021882/117696932-ba9c6100-b176-11eb-8ad1-5fedc7d75571.png)

3. ![Screen Shot 2021-05-10 at 11 13 15 AM](https://user-images.githubusercontent.com/3021882/117705286-baa15e80-b180-11eb-9efd-63e7d9e6742c.png)

**Comment by zugaldia** [comment] 2021-05-10 19:47
cc: @tobrun @LukasPaczos

**Comment by tobrun** [comment] 2021-05-11 09:55
> The new StyleObserver clears the list before notifying downstream observers

Yes this is expected behavior. The changes were done to optimize following use-case:

 - user attempts to load Style.Light and they provide a callback as part of the invocation
 - style errors out 
 - user attempts to load Style.Dark and they provide another callback as part of the invocation

Old behavior = invoke both callbacks
New behavior = invoke only latter callback by clearing any set callbacks when loading a new style

This said, StyleObserver is only responsible for managing the single shot callbacks that are passed when loading a new style: 
 - loadStyleUri 
 - loadStyleJson 
 - getStyle in async manner

And they are independent for listening to general style load changes through `MapboxMap#addOnStyleLoadedListener`.

----------------------------------------

A testrun using the testapp doesn't show any issues on our end

https://user-images.githubusercontent.com/2151639/117796538-77fa8780-b24f-11eb-9807-11cd80d6cc25.mp4

I'm wondering if we should change the logic in 1tap, looks very different from the logic we have today:

```
  override fun onStart() {
    super.onStart()
    mapView.onStart()
    mapView.location
      .addOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)
  }

  override fun onStop() {
    super.onStop()
    mapView.onStop()
    mapView.location
      .removeOnIndicatorPositionChangedListener(onIndicatorPositionChangedListener)
  }

```

**Comment by tobrun** [comment] 2021-05-11 10:48
Was able to find 2 issues that might be related:
 - #323 
 - #324

**Comment by zugaldia** [comment] 2021-09-02 14:03
Was this closed because it was expected (new) behavior?

**Comment by Zayankovsky** [comment] 2022-01-21 12:26
@tobrun the issue we currently see in 1TAP with this behavior is that if we call `loadStyleUri` after `onStart`, then location component fails to activate and puck is not shown. In order to solve this we have to manually call `mapView.location.onStart` in `loadStyleUri` callback. Is this expected behavior?

**Comment by LukasPaczos** [comment] 2022-01-26 11:47
Reopening to put this on the team's radar.

**Comment by yunikkk** [comment] 2022-01-27 17:48
Checked this issue in relation with https://github.com/mapbox/1tap-android/issues/1594. 
Root problem is that 1tap uses [null styleUri](https://github.com/mapbox/1tap-android/blob/24d8f6ab1e6546887f76ea5996b3355a20690625/map/src/main/java/com/mapbox/onetap/map/presentation/ui/MapFragment.kt#L430) on map creation and we don't handle this case well. 

The steps leading to issue are exactly as @kmadsen had described - 
1. LocationComponentPluginImpl waits for the style to arrive to init at [activateLocationComponent](https://github.com/mapbox/mapbox-maps-android/blob/main/plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt#L157), since there is not style initially set by MapOptions. 
2. Then style is requested, that clears the listener of LocationComponentPluginImpl
3. LocationComponent is never initialized and doesn't show up

In fact it can be any call, that triggers it to apply settings again, not `onStart` specifically.
Anyway seems like an issue on our end and should be fixed

**Closed** 2022-02-09 11:22 UTC
