### ISSUE TITLE
[v10.0.0-beta.15] sample app crashes on an emulator

### ISSUE THREAD

**Issue by OttyLab** [mapbox/mapbox-maps-android#163] opened 2021-03-08 13:00 UTC
## Environment

- Android OS version: x86 Emulator, API30
- Devices affected: Emulator
- Maps SDK Version: v10.0.0-beta.15

## Observed behavior and steps to reproduce

1. Run sample app
2. Click one of the example in the list
3. Crash happens (Crash does not happen on a physical device)

If you select "Annotation Circle", following crash happends.
```
2021-03-08 21:57:52.083 8052-8052/com.mapbox.maps.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.maps.testapp, PID: 8052
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.maps.testapp/com.mapbox.maps.testapp.examples.annotation.CircleActivity}: android.view.InflateException: Binary XML file line #6 in com.mapbox.maps.testapp:layout/activity_annotation: Binary XML file line #6 in com.mapbox.maps.testapp:layout/activity_annotation: Error inflating class com.mapbox.maps.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #6 in com.mapbox.maps.testapp:layout/activity_annotation: Binary XML file line #6 in com.mapbox.maps.testapp:layout/activity_annotation: Error inflating class com.mapbox.maps.MapView
     Caused by: android.view.InflateException: Binary XML file line #6 in com.mapbox.maps.testapp:layout/activity_annotation: Error inflating class com.mapbox.maps.MapView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.mapbox.maps.testapp.examples.annotation.CircleActivity.onCreate(CircleActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__ashldi3" referenced by "/data/app/com.mapbox.maps.testapp-kgqhTeFScsaz14qhLxtHkw==/lib/x86/libmapbox-maps.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
2021-03-08 21:57:52.083 8052-8052/com.mapbox.maps.testapp E/AndroidRuntime:     at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.mapbox.common.loader.MapboxLibraryLoader.load(MapboxLibraryLoader.kt:19)
        at com.mapbox.maps.loader.MapboxMapStaticInitializer.loadMapboxMapNativeLib(MapboxMapStaticInitializer.java:12)
        at com.mapbox.maps.MapController.<clinit>(MapController.kt:367)
        at com.mapbox.maps.MapView.<init>(MapView.kt:111)
        at com.mapbox.maps.MapView.<init>(MapView.kt:84)
        at com.mapbox.maps.MapView.<init>(MapView.kt:66)
        at com.mapbox.maps.MapView.<init>(MapView.kt:60)
        	... 27 more
2021-03-08 21:57:52.100 8052-8052/com.mapbox.maps.testapp I/Process: Sending signal. PID: 8052 SIG: 9

```

## Expected behavior

Crash does not happen

## Additional links and references

@mapbox/maps-android

**Comment by Chaoba** [comment] 2021-03-08 13:49
The issue is introduced by gl-native v10.0.0-beta.16
cc: @alexshalamov

**Comment by pengdev** [comment] 2021-03-12 13:35
Thanks for flagging, this is caused by the Android NDK version mismatch in the upstream dependencies, it will be resolved in the next release.

**Comment by tmpsantos** [comment] 2021-03-15 15:18
Just to clarify, are we talking about x86 (32-bits) here?

**Comment by OttyLab** [comment] 2021-03-16 00:56
@tmpsantos 
Yes, x86 (32bit). On x86_64, I do not see the crash so far.

**Comment by OttyLab** [comment] 2021-03-18 02:54
@tmpsantos @pengdev 

The same crash happened in the physical device below;

- Google Pixel 4a
- OS Level 30

The reproduce rate is quite low. Is this also cause by the same root cause?

**Comment by knov** [comment] 2021-03-18 14:21
This has been resolved and will be available with beta.16

**Closed** 2021-03-18 17:22 UTC
Labels: bug :beetle:
